name: Deploy

on:
  push:
    branches: [main]

jobs:
  check_version:
    name: Check version has been updated
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1
        with:
          diff-search: true

  build:
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test

  release:
    needs: [build, check_version]
    name: Create release tag
    runs-on: ubuntu-latest
    if: needs.check_version.outputs.version != ''

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ needs.check_version.outputs.version }}
          release_name: Release v${{ needs.check_version.outputs.version }}
          draft: false
          prerelease: false

  push_to_registry:
    needs: [build, check_version]
    name: Push docker image to registry
    runs-on: ubuntu-latest
    if: needs.check_version.outputs.version != ''

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to registry
        uses: docker/build-push-action@v2
        with:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/iex-ticker-alarm-bot
          tags: v${{ needs.check_version.outputs.version }}
          tag_with_sha: true
          tag_with_ref: true
