name: Release and publish

on:
  push:
    branches: [main]

jobs:
  check_version:
    name: Check version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.check.outputs.version }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Check if version has been updated
      id: check
      uses: EndBug/version-check@v1
      with:
        diff-search: true

    - name: Exit when unchanged
      if: steps.check.outputs.changed == 'false'
      run: exit 1

    - name: Exit when not found
      if: steps.check.outputs.changed == ''
      run: exit 1

  build:
    needs: check_version
    name: Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  release:
    needs: build
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ needs.check_version.outputs.version }}
          release_name: Release ${{ needs.check_version.outputs.version }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

  push_to_registry:
    needs: build
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: qweqwertr/iex-ticker-alarm-bot
          tag_with_ref: true
